training_config = {
    "num_options": 4,
    "batch_size": 128,
    "actors" : 1024,
    "num_steps" : 64,
    "num_minibatches" : 8,
    "update_epochs" : 4,
    "total_timesteps" : 1_000_000,
    "learning_rate" : 2.5e-4,
    "end_learning_rate" : 0,
    "adam_epsilon" : 1e-5,
    "max_grad_norm" : 0.5,
    "gamma": 0.99,
    "lambda": 0.8,
    "epsilon": 0.2,
    "epsilon_option": 0.1,
    "ent_coef": 0.01,
    "vf_coef": 0.5,
    "beta_coef": 0.1,
    "log_every": 1,
    "log": False,
}

large_run = {
    "num_options": 4,
    "actors" : 1024,
    "num_steps" : 64,
    "num_minibatches" : 8,
    "update_epochs" : 4,
    "total_timesteps" : 1_000_000_000,
    "learning_rate" : 2e-4,
    "end_learning_rate" : 0,
    "adam_epsilon" : 1e-5,
    "max_grad_norm" : 0.5,
    "gamma": 0.99,
    "lambda": 0.8,
    "epsilon": 0.2,
    "epsilon_option": 0.1,
    "ent_coef": 0.01,
    "vf_coef": 0.5,
    "beta_coef": 0.1,
    "log_every": 50,
    "log": True,
}

debug_config = {
    "num_options": 4,
    "actors" : 8,
    "num_steps" : 32,
    "num_minibatches" : 8,
    "update_epochs" : 4,
    "total_timesteps" : 1_000,
    "learning_rate" : 2.5e-4,
    "end_learning_rate" : 0,
    "adam_epsilon" : 1e-5,
    "max_grad_norm" : 0.5,
    "gamma": 0.99,
    "lambda": 0.8,
    "epsilon": 0.2,
    "epsilon_option": 0.1,
    "ent_coef": 0.01,
    "vf_coef": 0.5,
    "beta_coef": 0.1,
    "log_every": 1,
    "log": True,
}

debug_oc = {
    "num_options" : 4,
    "actors" : 8,
    "num_steps" : 32,
    "num_minibatches" : 8,
    "update_epochs" : 4,
    "total_timesteps" : 1_000,
    "learning_rate" : 2.5e-4,
    "end_learning_rate" : 0,
    "adam_epsilon" : 1e-5,
    "max_grad_norm" : 0.5,
    "gamma": 0.99,
    "epsilon": 0.2,
    "epsilon_option": 0.1,
    "ent_coef": 0.01,
    "beta_coef": 0.1,
    "log_every": 1,
    "log": True,
}