training_config = {
    "actors" : 256,
    "num_steps" : 128,
    "num_minibatches" : 64,
    "update_epochs" : 8,
    "total_timesteps" : 1_000_000,
    "learning_rate" : 2.5e-4,
    "end_learning_rate" : 0,
    "adam_epsilon" : 1e-5,
    "max_grad_norm" : 0.5,
    "gamma": 0.99,
    "lambda": 0.8,
    "epsilon": 0.2,
    "ent_coef": 0.01,
    "vf_coef": 0.5,
}

large_run = {
    "actors" : 1024,
    "num_steps" : 64,
    "num_minibatches" : 8,
    "update_epochs" : 4,
    "total_timesteps" : 1_000_000_000,
    "learning_rate" : 2e-4,
    "end_learning_rate" : 0,
    "adam_epsilon" : 1e-5,
    "max_grad_norm" : 0.5,
    "gamma": 0.99,
    "lambda": 0.8,
    "epsilon": 0.2,
    "ent_coef": 0.01,
    "vf_coef": 0.5,
}

debug_config = {
    "actors" : 8,
    "num_steps" : 32,
    "num_minibatches" : 8,
    "update_epochs" : 4,
    "total_timesteps" : 1_000,
    "learning_rate" : 2.5e-4,
    "end_learning_rate" : 0,
    "adam_epsilon" : 1e-5,
    "max_grad_norm" : 0.5,
    "gamma": 0.99,
    "lambda": 0.8,
    "epsilon": 0.2,
    "ent_coef": 0.01,
    "vf_coef": 0.5,
}